# Generated by Django 5.0.7 on 2024-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsrt_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('product', models.CharField(choices=[('Mobile 1', 'Mobile 1'), ('Mobile 2', 'Mobile 2'), ('Mobile 3', 'Mobile 3')], max_length=100)),
                ('enqiry_message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
