# Generated by Django 5.0.7 on 2024-07-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='firsrt_name',
            new_name='first_name',
        ),
    ]
