# Generated by Django 5.0.7 on 2024-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(choices=[('SELLER 1', 'SELLER 1'), ('SELLER 2', 'SELLER 2'), ('SELLER 3', 'SELLER 3')], default='SELLER 1', max_length=100),
        ),
    ]
